FROM ubuntu:16.04

ENV GOVC=https://github.com/vmware/govmomi/releases/download/v0.18.0/govc_linux_amd64.gz
ENV OVA=https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64.ova

RUN apt-get -qq update && apt-get install -y \
	curl python-pip \
	sudo

RUN curl -L $GOVC | gunzip > /usr/bin/govc && chmod +x /usr/bin/govc
COPY . /

# This isn't really needed for purely testing the automation
# ADD $OVA /bootstrap.ova

WORKDIR provision
RUN pip install ansible
RUN ansible-galaxy install -r external_roles.yml
# kernel update doesn't work in CI, requires reboot
RUN echo "---" > ~/.ansible/roles/concourse/tasks/kernel_update.yml
# Update version of concourse.
RUN mkdir -p group_vars/all
RUN echo "concourseci_version: \"v3.9.0\"" >> group_vars/all/vars.yml
# Workaround issue with wget and new user under docker
RUN sed -i.bak "s/{{ concourseci_user }}/root/" ~/.ansible/roles/concourse/tasks/install_nix.yml
CMD ["site.yml", "-i", "inventory"]
ENTRYPOINT [ "ansible-playbook" ]
